name: yahoo-finance-demo

channels:
  - conda-forge

dependencies:
  - python=3.7
  - jupyter
  - pandas=1.2.3
  - numpy=1.18.1
  - matplotlib=3.2.2
  - scikit-learn=0.24.1
  - PyYAML=5.3.1
  - gensim=3.8.3
  - scikit-learn=0.24.1
  - pip
  - pip:
      - seaborn==0.11.1
      - yfinance==0.1.59
